Alterando classes e criando testes.
mauriliomj/integra-prices pull request #1
Opened 2023-09-19 00:43 UTC by mauriliomj

…alterando a versão do java para tornar compativel com o swagger, criacao de testes unitários.

2023-09-19 02:50 UTC, progtiago requested changes

2023-09-19 02:50 UTC, progtiago commented on domains/Price.java
>      @NotNull(message = "{not.null}")
Imagino que esse NotNull seja uma validação que você queira fazer na camada http. Se for isso, o local adequado seria a PriceRequest, pois é na camada http que as validações de contratos devem ser postas.

2023-09-19 02:50 UTC, progtiago commented on gateways/inputs/controllers/PriceController.java
> +        return getPriceBySku.getPriceBySellerId(sellerID);
Apenas com o sellerId vc consegue obter o preço de um produto? Não faz muito sentido. Reavalie os contratos solicitados.

2023-09-19 02:50 UTC, progtiago commented on gateways/inputs/controllers/PriceController.java
>      @ApiOperation("Atualiza/modifica os preços cadastrados.")
Atualizar e modificar não é a mesma coisa?

2023-09-19 02:50 UTC, progtiago commented on gateways/inputs/controllers/PriceController.java
> +        updatePriceBySellerId.UpdatePriceBySellerId(sellerID, priceRequest.toDomain());
nome de método começando com maiúsculo está totalmente fora da convenção Java. Lembre-se dos padrões. o atributo sellerID também está fora da convenção em termos de nomeclatura, o correto seria sellerId. Onde você está lendo o campo sku que vc está recebendo via path?

2023-09-19 02:50 UTC, progtiago commented on gateways/outputs/PriceDataGateway.java
> +    boolean existsByPriceSku(String priceSku);
o sku é do produto, não do preço. Creio que você poderia chamar o parâmetro apenas de sku. Chamar de priceSku pode confundir o dev.

2023-09-19 02:50 UTC, progtiago commented on gateways/outputs/mongodb/PriceDataGatewayMongoImpl.java
> +        return priceRepository.findById(sellerId).map(PriceDocument::toDomain);
Não faz sentido o id do preço ser o sellerId. Pensa que nessa modelagem vc está dizendo que cada seller tem apenas um preço, quando na verdade, cada produto deste seller tem um preço distinto.

2023-09-19 02:50 UTC, progtiago commented on gateways/outputs/mongodb/PriceDataGatewayMongoImpl.java
> +        return priceRepository.existsById(sellerId);
Este método também parece não fazer sentido da forma como está escrito pela mesma razão do comentário que eu deixei no método "findById"

2023-09-19 02:50 UTC, progtiago commented on gateways/outputs/mongodb/PriceDataGatewayMongoImpl.java
> +    public boolean existsByPriceSku(String priceSku){
Prefira chamar apenas de sku pelas razões que descrevi nos comentários anteriores.

2023-09-19 02:50 UTC, progtiago commented on gateways/outputs/mongodb/documents/PriceDocument.java
> +    private String sellerId;
Não faz sentido o id do documento ser o sellerId.

2023-09-19 02:50 UTC, progtiago commented on usecases/AddPrice.java
>          price.setPriceSku(new PriceSku().toString());
Por que PriceSku é um objeto?

2023-09-19 02:50 UTC, progtiago commented on usecases/GetPriceBySellerId.java
> +    public Price getPriceBySellerId(String sellerId){
De qual sku é este preço?

2023-09-19 02:50 UTC, progtiago commented on usecases/UpdatePriceBySellerId.java
> +        Price updatePrice = priceDataGateway.findById(sellerId).orElseThrow(
De qual sku é este preço?

2023-09-26 12:23 UTC, mauriliomj commented on domains/Price.java
>      @NotNull(message = "{not.null}")
corrigido!

2023-09-26 12:24 UTC, mauriliomj commented on gateways/inputs/controllers/PriceController.java
> +        return getPriceBySku.getPriceBySellerId(sellerID);
Alterado para solicitar sku e sellerId.

2023-09-26 12:24 UTC, mauriliomj commented on gateways/inputs/controllers/PriceController.java
>      @ApiOperation("Atualiza/modifica os preços cadastrados.")
corrigido!

2023-09-26 12:26 UTC, mauriliomj commented on gateways/inputs/controllers/PriceController.java
> +        updatePriceBySellerId.UpdatePriceBySellerId(sellerID, priceRequest.toDomain());
Corrigida a nomeclatura e a recepção do sku via path.

2023-09-26 12:27 UTC, mauriliomj commented on gateways/outputs/PriceDataGateway.java
> +    boolean existsByPriceSku(String priceSku);
Corrigido!

2023-09-26 12:28 UTC, mauriliomj commented on gateways/outputs/mongodb/documents/PriceDocument.java
> +    private String sellerId;
Alterado para o sku.

2023-09-26 12:28 UTC, mauriliomj commented on usecases/AddPrice.java
>          price.setPriceSku(new PriceSku().toString());
Alterado para receber via path.

2023-09-26 12:45 UTC, mauriliomj commented on usecases/UpdatePriceBySellerId.java
> +        Price updatePrice = priceDataGateway.findById(sellerId).orElseThrow(
Foi alterado juntamente com as validações.

2023-09-26 12:45 UTC, mauriliomj commented on usecases/GetPriceBySellerId.java
> +    public Price getPriceBySellerId(String sellerId){
Foi alterado juntamente com as validações.

2023-10-03 01:10 UTC, progtiago requested changes

2023-10-03 01:10 UTC, progtiago commented on gateways/outputs/PriceDataGateway.java
>      Optional<Price> findById(String sellerId);
O que este método, que recebe um sellerId apenas, retorna? É possível obter um preço apenas tendo o sellerId em mãos?

2023-10-03 01:10 UTC, progtiago commented on usecases/AddPrice.java
> +        boolean skuExists = priceDataGateway.findBySku(sku).isPresent();
Ao adiconar um novo preço, é importante validar se aquele produto que aquele seller vende já não possui preço cadastrado. A lógica que vc implementou aqui não satisfaz este requisito.

2023-10-03 01:11 UTC, progtiago commented on gateways/inputs/controllers/PriceController.java
> +        return getPriceBySku.getPriceBySellerId(sellerID);
Pelo código que eu vi apenas o sellerId está sendo solicitado.

2023-10-10 01:49 UTC, progtiago approved these changes

2023-10-10 01:49 UTC, merged